### ISSUE TITLE
Unhandled error when streaming data

### ISSUE THREAD

**Issue by dionjwa** [Autodesk/cloudcomputecannon#33]
{"name":"cloudcomputecannon","hostname":"578f5d1771fe","pid":15,"level":50,"error":"Error: ECONNABORTED: software caused connection abort, close\n    at Error (native)","file":"tirrenu_cache/1b9653ea7b4d37550f13b62eab6d1317/surface/outputs/molecule/surface/14.pf","message":"Error reading file","src":{"file":"StorageRestApi.hx","line":34},"time":"2016-07-20T21:41:28.414Z","msg":"","v":0}
compute_1        | {"name":"cloudcomputecannon","hostname":"578f5d1771fe","pid":15,"level":60,"crash":"Error: Can't set headers after they are sent.\n    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)\n    at ServerResponse.header (/app/node_modules/express/lib/response.js:719:10)\n    at ServerResponse.contentType (/app/node_modules/express/lib/response.js:552:15)\n    at ServerResponse.send (/app/node_modules/express/lib/response.js:139:14)\n    at ReadStream.<anonymous> (/app/build/file:/app/src/haxe/ccc/storage/StorageRestApi.hx:35:17)\n    at ReadStream.g (events.js:260:16)\n    at emitOne (events.js:77:13)\n    at ReadStream.emit (events.js:169:7)\n    at fs.js:1770:14\n    at FSReqWrap.oncomplete (fs.js:82:15)","message":"crash","src":{"file":"ServerCompute.hx","line":90},"time":"2016-07-20T21:41:29.035Z","msg":"","v":0}

**Comment by dionjwa** [comment]
Fixed in a7ab26cb00129100095e9995d23c69ddd50a929d
